language: python
python:
- 3.6
- 3.5
- 3.4
- 3.7-dev
- nightly
- pypy
- pypy3
#- 2.7
matrix:
  allow_failures:
  - python: nightly
  - python: 3.7-dev
services:
- docker
before_install:
- sudo service docker restart ; sleep 10  # https://github.com/travis-ci/travis-ci/issues/4778
- docker run -d --publish=28015:28015 rethinkdb
install:
- pip install git+https://github.com/jkafader/snakebite@feature/python3
- pip install -e . --no-input --upgrade
script:
- python -m inittest discover