---
# File: tasks/main.yml - Main tasks for Trough Sync Servers

- name: Add Trough user
  become: true
  user:
    name: trough
    comment: "Trough User"
    group: bin
    createhome: no

- name: Ensure Trough user can write to venv_root
  become: true
  file:
    path: /opt
    group: bin
    mode: 0775

- name: Ensure Trough is installed
  become: true
  become_user: "{{user}}"
  git: repo={{trough_git_url}} version={{trough_git_branch}} dest={{venv_root}}/trough-ve34

- name: Install sync-server systemd unit file
  become: true
  template:
    src: sync-server.j2
    dest: "/etc/systemd/system/sync-server.service"

- name: "Start sync-server" 
  become: true
  systemd: state=started name="sync-server" daemon_reload=yes

- name: Install write-provisioner systemd unit file
  become: true
  template:
    src: write-provisioner.j2
    dest: "/etc/systemd/system/write-provisioner.service"

- name: Start write-provisioner
  become: true
  systemd: state=started name=write-provisioner daemon_reload=yes
