---
# File: tasks/main.yml - Main tasks for Trough Sync Servers

- name: Add Trough user
  become: true
  user:
    name: trough
    comment: "Trough User"
    group: bin
    createhome: no

- name: Ensure Trough user can write to venv_root
  become: true
  file:
    path: "{{ venv_root }}"
    group: bin
    mode: 0775

- name: Install Trough
  become: true
  become_user: "{{user}}"
  pip: name="git+{{trough_git_url}}@{{trough_git_branch}}#egg=trough"
       virtualenv="{{venv_root}}/trough-ve3"
       virtualenv_python=python3
       editable=false
       extra_args='--no-input --upgrade --pre --index-url https://devpi.archive.org/ait/packages/+simple/'

- name: Install sync-server init.d shell script
  become: true
  vars:
    daemon: "{{ venv_root }}/trough-ve3/bin/sync.py"
    daemon_args: --server
    service_name: sync-server
    service_description: Trough Sync Server
  template:
    src: initd-skeleton.j2
    dest: "/etc/init.d/sync-server"
    owner: root
    mode: 0744

- name: "Start sync-server" 
  become: true
  service:
    name: sync-server
    enabled: yes
    state: started

- name: Install write-provisioner init.d shell script
  become: true
  vars:
    daemon: "{{venv_root}}/trough-ve3/bin/uwsgi"
    daemon_args: "--http :{{sync_port}} --wsgi-file {{venv_root}}/trough-ve3/bin/write_provisioner_server.py"
    service_name: write-provisioner
    service_description: Trough Sync Write Provisioner
  template:
    src: initd-skeleton.j2
    dest: "/etc/init.d/write-provisioner"
    owner: root
    mode: 0744

- name: Start write-provisioner
  become: true
  service:
    name: write-provisioner
    enabled: yes
    state: started
