---
# File: tasks/main.yml - Main tasks for Trough Sync Servers

- name: Add Trough user
  become: true
  user:
    name: trough
    comment: "Trough User"
    group: bin
    createhome: no

- name: Ensure Trough user can write to venv_root
  become: true
  file:
    path: "{{ venv_root }}"
    group: bin
    mode: 0775

- name: Install Trough
  become: true
  become_user: "{{user}}"
  pip: name="git+{{trough_git_url}}@{{trough_git_branch}}#egg=trough"
       virtualenv="{{venv_root}}/trough-ve3"
       virtualenv_python=python3
       editable=false
       extra_args='--no-input --upgrade --pre --index-url https://devpi.archive.org/ait/packages/+simple/'

- name: Install sync-server supervised by daemontools in /etc/service
  become: true
  vars:
    command: "{{ venv_root }}/trough-ve3/bin/sync.py --server"
  template:
    src: service-skeleton.j2
    dest: "/etc/service/sync-server"
    owner: root
    mode: 0755

- name: Install daemontools logging for sync-server
  become: true
  vars:
    command: "setuidgid {{user}} multilog t ./main"
  template:
    src: service-skeleton.j2
    dest: "/etc/service/sync-server/log/run"
    owner: "{{user}}"
    mode: 0755

- name: "Start sync-server" 
  become: true
  svc:
    name: sync-server
    enabled: yes
    state: started
    service_dir: "/etc/service/sync-server"

- name: Install write-provisioner supervised by daemontools in /etc/service
  become: true
  vars:
    command: "{{venv_root}}/trough-ve3/bin/uwsgi --http :{{sync_port}} --die-on-term --wsgi-file {{venv_root}}/trough-ve3/bin/write_provisioner_server.py"
  template:
    src: service-skeleton.j2
    dest: "/etc/service/write-provisioner"
    owner: root
    mode: 0755

- name: Install daemontools logging for write-provisioner
  become: true
  vars:
    command: "setuidgid {{user}} multilog t ./main"
  template:
    src: service-skeleton.j2
    dest: "/etc/service/write-provisioner/log/run"
    owner: "{{user}}"
    mode: 0755

- name: Start write-provisioner
  become: true
  svc:
    name: write-provisioner
    enabled: yes
    state: started
    service_dir: "/etc/service/write-provisioner"
