---
# File: tasks/main.yml - Main tasks for Trough Sync Servers

- name: Add Trough user
  become: true
  user:
    name: trough
    comment: "Trough User"
    group: bin
    createhome: no

- name: Ensure Trough user can write to venv_root
  become: true
  file:
    path: /opt
    group: bin
    mode: 0775

- name: Ensure Trough is installed
  become: true
  become_user: "{{user}}"
  git: repo={{trough_git_url}} version={{trough_git_branch}} dest={{venv_root}}/trough-ve3

- name: Install sync-server init.d shell script
  become: true
  vars:
    daemon: "{{ venv_root }}/trough-ve3/trough/sync.py"
    daemon_args: --server
    service_name: sync-server
    service_description: Trough Sync Server
  template:
    src: initd-skeleton.j2
    dest: "/etc/init.d/sync-server"
    owner: root
    mode: 0744

- name: "Start sync-server" 
  become: true
  service:
    name: sync-server
    enabled: yes
    state: started

- name: Install write-provisioner init.d shell script
  become: true
  vars:
    daemon: "{{venv_root}}/trough-ve3/bin/uwsgi"
    daemon_args: "{{venv_root}}/trough-ve3/trough/sync.py"
    service_name: write-provisioner
    service_description: Trough Sync Write Provisioner
  template:
    src: initd-skeleton.j2
    dest: "/etc/init.d/write-provisioner"
    owner: root
    mode: 0744

- name: Start write-provisioner
  become: true
  service:
    name: write-provisioner
    enabled: yes
    state: started
