---
# File: tasks/main.yml - Main tasks for Trough Sync Servers

- name: Add Trough user
  become: true
  user:
    name: trough
    comment: "Trough User"
    group: bin
    createhome: no

- name: Ensure Trough user can write to venv_root
  become: true
  file:
    path: "{{ venv_root }}"
    group: bin
    mode: 0775

- name: Ensure /var/log logging files are in place
  become: true
  file:
    path: "/var/log/{{item}}.log"
    state: touch
    owner: "{{user}}"
  with_items:
    - trough-sync-server
    - trough-segment-manager

- name: Ensure daemontools service directories are in place
  become: true
  file:
    path: "/etc/service/{{item}}"
    state: directory
    owner: root
  with_items:
    - trough-sync-server
    - trough-sync-server/log
    - trough-segment-manager
    - trough-segment-manager/log

- name: Install logrotate.d rotation scripts for local trough logs
  become: true
  template:
    src: fifo-log-rotator.j2
    dest: "/etc/logrotate.d/{{item.name}}"
    owner: root
    mode: 0644  
  with_items:
    - name: trough-sync-server
    - name: trough-segment-manager

- name: Install Trough
  become: true
  become_user: "{{user}}"
  pip: name="git+{{trough_git_url}}@{{trough_git_branch}}#egg=trough"
       virtualenv="{{venv_root}}/trough-ve3"
       virtualenv_python=python3
       editable=false
       extra_args='--no-input --upgrade --pre --index-url https://devpi.archive.org/ait/packages/+simple/'

- name: Install trough-sync-server supervised by daemontools in /etc/service
  become: true
  vars:
    command: "setuidgid {{ user }} {{ venv_root }}/trough-ve3/bin/sync.py --server"
    name: trough-sync-server
  template:
    src: service-skeleton.j2
    dest: "/etc/service/trough-sync-server/run"
    owner: root
    mode: 0755

- name: Install trough-sync-server fifo log reader supervised by daemontools in /etc/service/trough-sync-server
  become: true
  vars:
    name: trough-sync-server
    udp_dest: "{{udp_log_host}}:{{sync_server_udp_log_port}}"
  template:
    src: fifo-log-reader-skeleton.j2
    dest: "/etc/service/trough-sync-server/log/run"
    owner: root
    mode: 0755

- name: "Start trough-sync-server"
  become: true
  svc:
    name: trough-sync-server
    enabled: yes
    state: restarted
    service_dir: "/etc/service/trough-sync-server"

- name: "Start trough-sync-server fifo log reader"
  become: true
  svc:
    name: log
    enabled: yes
    state: restarted
    service_dir: "/etc/service/trough-sync-server/"

- name: Install trough-segment-manager supervised by daemontools in /etc/service
  become: true
  vars:
    command: "{{venv_root}}/trough-ve3/bin/uwsgi --http :{{sync_server_port}} --uid={{user}} --route-run=chunked: --master --processes=2 --max-requests=50000 --vacuum --die-on-term --http-timeout=900 --mount /=trough.wsgi.segment_manager:server"
    name: trough-segment-manager
  template:
    src: service-skeleton.j2
    dest: "/etc/service/trough-segment-manager/run"
    owner: root
    mode: 0755

- name: Install trough-segment-manager fifo log reader supervised by daemontools in /etc/service/trough-segment-manager
  become: true
  vars:
    name: trough-segment-manager
    udp_dest: "{{udp_log_host}}:{{write_provisioner_server_udp_log_port}}"
  template:
    src: fifo-log-reader-skeleton.j2
    dest: "/etc/service/trough-segment-manager/log/run"
    owner: root
    mode: 0755

- name: Start trough-segment-manager
  become: true
  svc:
    name: trough-segment-manager
    enabled: yes
    state: restarted
    service_dir: "/etc/service/trough-segment-manager"

- name: "Start trough-segment-manager fifo log reader"
  become: true
  svc:
    name: log
    enabled: yes
    state: restarted
    service_dir: "/etc/service/trough-segment-manager"

- name: Remove old path for trough write provisioner
  become: true
  file:
    state: absent
    path: "/etc/service/trough-write-provisioner/"

- name: Restart daemontools to pick up any logging configuration changes
  become: true
  systemd:
    name: daemontools
    state: restarted
