---
# File: tasks/main.yml - Main tasks for Trough Sync Servers

- name: Add Trough user
  become: true
  user:
    name: trough
    comment: "Trough User"
    group: bin
    createhome: no

- name: Ensure Trough user can write to venv_root
  become: true
  file:
    path: "{{ venv_root }}"
    group: bin
    mode: 0775

- name: Ensure /var/log logging files are in place
  become: true
  file:
    path: "/var/log/{{item}}.log"
    state: touch
    owner: "{{user}}"
  with_items:
    - sync-server
    - write-provisioner

- name: Ensure daemontools service directories are in place
  become: true
  file:
    path: "/etc/service/{{item}}"
    state: directory
    owner: root
  with_items:
    - sync-server
    - write-provisioner

- name: Install Trough
  become: true
  become_user: "{{user}}"
  pip: name="git+{{trough_git_url}}@{{trough_git_branch}}#egg=trough"
       virtualenv="{{venv_root}}/trough-ve3"
       virtualenv_python=python3
       editable=false
       extra_args='--no-input --upgrade --pre --index-url https://devpi.archive.org/ait/packages/+simple/'

- name: Install sync-server supervised by daemontools in /etc/service
  become: true
  vars:
    command: "{{ venv_root }}/trough-ve3/bin/sync.py --server >> /var/log/sync-server.log 2>&1"
  template:
    src: service-skeleton.j2
    dest: "/etc/service/sync-server/run"
    owner: root
    mode: 0755

- name: "Start sync-server" 
  become: true
  svc:
    name: sync-server
    enabled: yes
    state: started
    service_dir: "/etc/service/sync-server"

- name: Install write-provisioner supervised by daemontools in /etc/service
  become: true
  vars:
    command: "{{venv_root}}/trough-ve3/bin/uwsgi --http :{{sync_port}} --uid={{user}} --master --processes=2 --harakiri=20 --max-requests=50000 --vacuum --die-on-term --logto2=/var/log/write-provisioner.log --wsgi-file {{venv_root}}/trough-ve3/bin/write_provisioner_server.py"
  template:
    src: service-skeleton.j2
    dest: "/etc/service/write-provisioner/run"
    owner: root
    mode: 0755

- name: Start write-provisioner
  become: true
  svc:
    name: write-provisioner
    enabled: yes
    state: started
    service_dir: "/etc/service/write-provisioner"
