- name: Open Consul firewall ports
  become_user: root
  become: true
  vars:
    begin_port: 6300
    end_port: 6600
  template:
    src: templates/open-ports.ferm.j2
    dest: /etc/ferm/input/cluster.consul.ports

- name: Open Consul DNS ports
  become_user: root
  become: true
  vars:
    dns_port: 53
    consul_dns_port: 6600
  template:
    src: templates/open-dns-port.ferm.j2
    dest: /etc/ferm/input/cluster.consul.dns.port

- name: Open Trough firewall ports
  become_user: root
  become: true
  vars:
    begin_port: "{{ sync_port }}"
    end_port: "{{ read_port }}"
  template:
    src: templates/open-ports.ferm.j2
    dest: /etc/ferm/input/cluster.trough.ports

- name: Reload FERM configuration
  become: true
  service:
    name: ferm
    state: reloaded
