---
- name: ensure required packages are installed
  become: true
  apt: name={{item}} state=present
  with_items:
  - git
  - gcc
  - python3-dev
  - daemontools-run
  - libasn1-8-heimdal
  - libc6
  - libcomerr2
  - libcurl3
  - libffi6
  - libgcc1
  - libgmp10
  - libgnutls30
  - libgsasl7
  - libgssapi-krb5-2
  - libgssapi3-heimdal
  - libhcrypto4-heimdal
  - libheimbase1-heimdal
  - libheimntlm0-heimdal
  - libhogweed4
  - libhx509-5-heimdal
  - libicu55
  - libidn11
  - libk5crypto3
  - libkeyutils1
  - libkrb5-26-heimdal
  - libkrb5-3
  - libkrb5support0
  - libldap-2.4-2
  - liblzma5
  - libnettle6
  - libntlm0
  - libp11-kit0
  - libroken18-heimdal
  - librtmp1
  - libsasl2-2
  - libsqlite3-0
  - libssl1.0.0
  - libstdc++6
  - libtasn1-6
  - libuuid1
  - libwind0-heimdal
  - libxml2
  - zlib1g
  - libsqlite3-dev

# get recent virtualenv, which bundles a recent pip
- command: mktemp -d
  register: mktempd_out
- name: download virtualenv-15.1.0
  become: true
  get_url:
    url: https://pypi.python.org/packages/d4/0c/9840c08189e030873387a73b90ada981885010dd9aea134d6de30cd24cb8/virtualenv-15.1.0.tar.gz
    dest: '{{mktempd_out.stdout}}'
    checksum: sha1:995ce0fa007210ac2f10258999d06813ecdd6eeb
- name: extract virtualenv-15.1.0.tar.gz
  unarchive: src={{mktempd_out.stdout}}/virtualenv-15.1.0.tar.gz dest={{mktempd_out.stdout}} copy=no
- name: run "python3 setup.py install" in {{mktempd_out.stdout}}/virtualenv-15.1.0
  become: true
  command: python3 setup.py install
           chdir={{mktempd_out.stdout}}/virtualenv-15.1.0
           creates=/usr/local/lib/python3.*/dist-packages/virtualenv-15.1.0-py3.*.egg/virtualenv.py
- file:
    path: '{{mktempd_out.stdout}}'
    state: absent
  become: true
  become_user: root

# this debug message produces the below output on Ubuntu xenial:
#- debug:
#    msg: "System {{ inventory_hostname }} has os_family: {{ ansible_os_family }} and distribution_major_version: {{ ansible_distribution_major_version }}"
# ok: [wbgrp-svc111] => {
#    "msg": "System wbgrp-svc111 has os_family: Debian and distribution_major_version: 16"
# }
- name: Include ferm firewall rules if we are on Ubuntu xenial
  when: ansible_os_family == "Debian" and ansible_distribution_major_version == "16"
  include: ferm_firewall.yml

- name: Create Trough Configuration Directory
  become: true
  file:
    path: "/etc/trough"
    state: directory
    owner: root

- name: Install Trough Configuration
  become: true
  template:
    src: settings.j2
    dest: "/etc/trough/settings.yml"
    owner: root
    mode: 0644

- name: Install libhdfs3
  become: true
  apt:
    deb: https://github.com/jkafader/libhdfs3-deb/raw/master/libhdfs3_1-1-xenial-x86_64.deb

