---
user: trough
venv_root: /opt
read_port: 6444
write_port: 6222
sync_port: 6111
minimum_assignments: "lambda segment_id: 2 if segment_id.isnumeric() and int(segment_id) > 200000 else 1"
hdfs_host: null
hdfs_port: 8000
