- name: ensure consul is installed
  local_action: command ansible-galaxy install -r requirements.yml
- name: ensure trough is installed
  become: true
  become_user: "{{user}}"
  git: repo={{trough_git_url}} version={{trough_git_branch}} dest={{venv_root}}/trough-ve34
- name: install trough dependencies
  become: true
  become_user: "{{user}}"
  pip: requirements={{venv_root}}/trough-ve34/requirements.txt
       virtualenv={{venv_root}}/trough-ve34 virtualenv_python=python3.4
       editable=false
       extra_args='--no-input --upgrade --pre --index-url https://devpi.archive.org/ait/packages/+simple/'

- name: install sync-local systemd unit file
  template: src=sync-local.j2 dest=/etc/systemd/system/sync-local.service
- name: start sync-local
  systemd: state=started name=sync-local daemon_reload=yes

- name: install trough-write systemd unit file
  template: src=trough-write.j2 dest=/etc/systemd/system/trough-write.service
- name: start trough-write
  systemd: state=started name=trough-write daemon_reload=yes

- name: install trough-read systemd unit file
  template: src=trough-write.j2 dest=/etc/systemd/system/trough-write.service
- name: start trough-read
  systemd: state=started name=trough-read daemon_reload=yes
