---
# File: tasks/main.yml - Main tasks for Trough Worker Nodes

- name: Add Trough user
  become: true
  user:
    name: trough
    comment: "Trough User"
    group: bin
    createhome: no

- name: Ensure Trough user can write to local_data
  become: true
  file:
    path: "{{ local_data }}"
    state: directory
    group: bin
    owner: trough
    mode: 0775

- name: Ensure Trough user can write to venv_root
  become: true
  file:
    path: "{{ venv_root }}"
    group: bin
    mode: 0775

- name: Ensure /var/log logging files are in place
  become: true
  file:
    path: "/var/log/{{item}}.log"
    state: touch
    owner: "{{user}}"
  with_items:
    - trough-sync-local
    - trough-write
    - trough-read
    - trough-write-provisioner-local

- name: Ensure daemontools service directories are in place
  become: true
  file:
    path: "/etc/service/{{item}}"
    state: directory
    owner: root
  with_items:
    - trough-sync-local
    - trough-write
    - trough-read
    - trough-write-provisioner-local

- name: Install Trough
  become: true
  become_user: "{{user}}"
  pip: name="git+{{trough_git_url}}@{{trough_git_branch}}#egg=trough"
       virtualenv="{{venv_root}}/trough-ve3"
       virtualenv_python=python3
       editable=false
       extra_args='--no-input --upgrade --pre --index-url https://devpi.archive.org/ait/packages/+simple/'

- name: Install trough-sync-local supervised by daemontools in /etc/service
  become: true
  vars:
    command: "sudo -u {{ user }} {{ venv_root }}/trough-ve3/bin/sync.py >> /var/log/trough-sync-local.log 2>&1"
  template:
    src: service-skeleton.j2
    dest: "/etc/service/trough-sync-local/run"
    owner: root
    mode: 0755

- name: "Start trough-sync-local"
  become: true
  svc:
    name: trough-sync-local
    enabled: yes
    state: restarted
    service_dir: "/etc/service/trough-sync-local"

- name: Install trough-write supervised by daemontools in /etc/service
  become: true
  vars:
    command: "{{venv_root}}/trough-ve3/bin/uwsgi --http :{{write_port}} --uid={{ user }} --master --processes=2 --harakiri=240 --max-requests=50000 --vacuum --die-on-term --logto2=/var/log/trough-write.log --wsgi-file {{venv_root}}/trough-ve3/bin/writer.py"
  template:
    src: service-skeleton.j2
    dest: "/etc/service/trough-write/run"
    owner: root
    mode: 0755

- name: Start trough-write
  become: true
  svc:
    name: trough-write
    enabled: yes
    state: restarted
    service_dir: "/etc/service/trough-write"

- name: Install trough-read supervised by daemontools in /etc/service
  become: true
  vars:
    command: "{{venv_root}}/trough-ve3/bin/uwsgi --http :{{read_port}} --uid={{user}} --master --processes=2 --harakiri=3200 --socket-timeout=3200 --max-requests=50000 --vacuum --die-on-term --logto2=/var/log/trough-read.log --wsgi-file {{venv_root}}/trough-ve3/bin/reader.py"
  template:
    src: service-skeleton.j2
    dest: "/etc/service/trough-read/run"
    owner: root
    mode: 0755


- name: Start trough-read
  become: true
  svc:
    name: trough-read
    enabled: yes
    state: restarted
    service_dir: "/etc/service/trough-read"

- name: Install trough-write-provisioner-local supervised by daemontools in /etc/service
  become: true
  vars:
    command: "{{venv_root}}/trough-ve3/bin/uwsgi --http :{{sync_port}} --uid={{user}} --master --processes=2 --harakiri=20 --max-requests=50000 --vacuum --die-on-term --logto2=/var/log/trough-write-provisioner-local.log --wsgi-file {{venv_root}}/trough-ve3/bin/write_provisioner_local.py"
  template:
    src: service-skeleton.j2
    dest: "/etc/service/trough-write-provisioner-local/run"
    owner: root
    mode: 0744

- name: Start trough-write-provisioner-local
  become: true
  svc:
    name: trough-write-provisioner-local
    enabled: yes
    state: restarted
    service_dir: "/etc/service/trough-write-provisioner-local"
